// Generated by GAS WebApp Builder | Created by @farhanalfaizi

function doGet(e) {
  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('JID - SMK Jugra')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// ==========================================
// 1. DATABASE SETUP
// ==========================================
function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  // Sheet: Dokumen
  let sheetDokumen = ss.getSheetByName('Dokumen');
  if (!sheetDokumen) {
    sheetDokumen = ss.insertSheet('Dokumen');
    sheetDokumen.appendRow(['id', 'tajuk', 'kategori', 'tahun_sesi', 'tarikh', 'penerangan', 'link_fail', 'tag', 'keizinan', 'created_at']);
    sheetDokumen.setFrozenRows(1);
    sheetDokumen.getRange('A1:J1').setBackground('#0284c7').setFontColor('white').setFontWeight('bold'); // Tema Baby Blue
  } else {
    const headers = sheetDokumen.getRange(1, 1, 1, sheetDokumen.getLastColumn()).getValues()[0];
    const req = ['id', 'tajuk', 'kategori', 'tahun_sesi', 'tarikh', 'penerangan', 'link_fail', 'tag', 'keizinan', 'created_at'];
    req.forEach(function(h) {
      if (headers.indexOf(h) === -1) {
        sheetDokumen.getRange(1, headers.length + 1).setValue(h);
        headers.push(h);
      }
    });
  }

  // Sheet: Users
  let sheetUsers = ss.getSheetByName('Users');
  if (!sheetUsers) {
    sheetUsers = ss.insertSheet('Users');
    sheetUsers.appendRow(['username', 'password', 'fullname', 'role']);
    // Password Admin default: Admin@2026 (hashed).
    sheetUsers.appendRow(['admin', hashPassword('Admin@2026'), 'Mohd Naudi Haqqi bin Ahmad', 'Admin']);
    sheetUsers.appendRow(['guru', hashPassword('Admin@2026'), 'Guru Bertugas', 'Guru']);
    sheetUsers.setFrozenRows(1);
    sheetUsers.getRange('A1:D1').setBackground('#0284c7').setFontColor('white').setFontWeight('bold'); // Tema Baby Blue
  }

  // Sheet: AuditLog
  let sheetLog = ss.getSheetByName('AuditLog');
  if (!sheetLog) {
    sheetLog = ss.insertSheet('AuditLog');
    sheetLog.appendRow(['timestamp', 'username', 'action', 'detail']);
    sheetLog.setFrozenRows(1);
    sheetLog.getRange('A1:D1').setBackground('#e0f2fe').setFontColor('#0284c7').setFontWeight('bold'); // Tema Soft Blue
  }
}

// ==========================================
// 2. SECURITY & UTILITIES (ENHANCED)
// ==========================================
function hashPassword(password) {
  var rawHash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password);
  var txtHash = '';
  for (var i = 0; i < rawHash.length; i++) {
    var hashVal = rawHash[i];
    if (hashVal < 0) hashVal += 256;
    if (hashVal.toString(16).length === 1) txtHash += '0';
    txtHash += hashVal.toString(16);
  }
  return txtHash;
}

function generateSessionToken(username) {
  var token = Utilities.getUuid();
  var cache = CacheService.getScriptCache();
  cache.put('session_' + token, JSON.stringify({ username: username, created: new Date().toISOString() }), 28800); // 8 hours
  cache.put('user_session_' + username, token, 28800);
  return token;
}

function validateSession(token) {
  if (!token) return { valid: false, message: 'Token tidak dijumpai' };
  var cache = CacheService.getScriptCache();
  var sessionData = cache.get('session_' + token);
  if (!sessionData) return { valid: false, message: 'Sesi tamat. Sila log masuk semula.' };
  try {
    var parsed = JSON.parse(sessionData);
    return { valid: true, username: parsed.username };
  } catch (e) {
    return { valid: false, message: 'Token tidak sah' };
  }
}

function destroySession(token) {
  var cache = CacheService.getScriptCache();
  var sessionData = cache.get('session_' + token);
  if (sessionData) {
    try {
      var parsed = JSON.parse(sessionData);
      cache.remove('user_session_' + parsed.username);
    } catch (e) {}
  }
  cache.remove('session_' + token);
  return { success: true };
}

function checkLoginRateLimit(username) {
  var cache = CacheService.getScriptCache();
  var key = 'login_fail_' + username;
  var failCount = parseInt(cache.get(key) || '0');
  if (failCount >= 5) return { allowed: false, message: 'Akaun dikunci sementara. Sila cuba lagi selepas 15 minit.' };
  return { allowed: true, failCount: failCount };
}

function recordLoginFailure(username) {
  var cache = CacheService.getScriptCache();
  var key = 'login_fail_' + username;
  var failCount = parseInt(cache.get(key) || '0') + 1;
  cache.put(key, String(failCount), 900); // Lock 15 min
}

function clearLoginFailures(username) {
  CacheService.getScriptCache().remove('login_fail_' + username);
}

function logAction(username, action, detail) {
  try {
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('AuditLog');
    if (sheet) sheet.appendRow([new Date(), username || 'SYSTEM', action, String(detail || '').substring(0, 500)]);
  } catch (e) {}
}

function requireRole(token, requiredRole) {
  var session = validateSession(token);
  if (!session.valid) return { authorized: false, message: session.message, sessionExpired: true };
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  var map = getColumnMap(sheet);
  var data = sheet.getDataRange().getValues();
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][map['username']]) === session.username) {
      var userRole = String(data[i][map['role']]);
      if (userRole === requiredRole || userRole === 'Admin') {
        return { authorized: true, username: session.username, role: userRole };
      }
      break;
    }
  }
  return { authorized: false, message: 'Anda tiada akses untuk fungsi ini.' };
}

function safeDateFormat(value) {
  if (!value) return '';
  if (value instanceof Date) return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  return String(value);
}

function getColumnMap(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  const map = {};
  headers.forEach(function(h, i) { map[String(h).toLowerCase().trim()] = i; });
  return map;
}

function sanitizeInput(value, maxLength) {
  if (!value) return '';
  maxLength = maxLength || 500;
  return String(value).replace(/<[^>]*>/g, '').trim().substring(0, maxLength);
}

// ==========================================
// 3. AUTHENTICATION API
// ==========================================
function loginUser(username, password) {
  var rateCheck = checkLoginRateLimit(username);
  if (!rateCheck.allowed) return { success: false, message: rateCheck.message };

  username = String(username).trim().substring(0, 50);
  password = String(password).trim();
  if (!username || !password) return { success: false, message: 'ID dan Kata Laluan wajib diisi.' };

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  if (!sheet) return { success: false, message: 'Pangkalan data tidak wujud. Sila jalankan setupDatabase().' };

  var data = sheet.getDataRange().getValues();
  var map = getColumnMap(sheet);
  var hashedInput = hashPassword(password);

  for (var i = 1; i < data.length; i++) {
    if (String(data[i][map['username']]).trim() === username && String(data[i][map['password']]).trim() === hashedInput) {
      clearLoginFailures(username);
      var token = generateSessionToken(username);
      logAction(username, 'LOGIN', 'Log masuk berjaya');
      return {
        success: true,
        token: token,
        user: { username: data[i][map['username']], fullname: data[i][map['fullname']], role: data[i][map['role']] }
      };
    }
  }

  recordLoginFailure(username);
  return { success: false, message: 'ID atau Kata Laluan salah!' };
}

// ==========================================
// 4. DOKUMEN CRUD API (PUBLIC & SECURE)
// ==========================================
function getDokumen(token) {
  // Tetapan asal adalah Public
  var role = 'Public';
  
  // Semak jika ada token yang sah dihantar
  if (token) {
    var session = validateSession(token);
    if (session.valid) {
      var sheetUsers = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
      if (sheetUsers) {
        var dataUsers = sheetUsers.getDataRange().getValues();
        var mapUsers = getColumnMap(sheetUsers);
        for (var j = 1; j < dataUsers.length; j++) {
          if (String(dataUsers[j][mapUsers['username']]) === session.username) {
            role = String(dataUsers[j][mapUsers['role']]);
            break;
          }
        }
      }
    } else {
      // Token tidak sah (Expired), arahkan Frontend untuk log keluar
      return { success: false, message: session.message, sessionExpired: true };
    }
  }

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Dokumen');
  if (!sheet || sheet.getLastRow() <= 1) return { success: true, data: [] };

  var map = getColumnMap(sheet);
  var data = sheet.getDataRange().getValues();
  var result = [];

  for (var i = 1; i < data.length; i++) {
    var row = data[i];
    var keizinan = row[map['keizinan']] || 'Umum';
    
    // PENAPIS KESELAMATAN (SERVER-SIDE)
    if (role === 'Public' && keizinan !== 'Umum') continue;
    if (role === 'Guru' && keizinan === 'Admin') continue;

    result.push({
      id: row[map['id']] || '',
      tajuk: row[map['tajuk']] || '',
      kategori: row[map['kategori']] || '',
      tahun_sesi: row[map['tahun_sesi']] || '',
      tarikh: safeDateFormat(row[map['tarikh']]),
      penerangan: row[map['penerangan']] || '',
      link_fail: row[map['link_fail']] || '',
      tag: row[map['tag']] || '',
      keizinan: keizinan,
      created_at: safeDateFormat(row[map['created_at']])
    });
  }
  
  result.sort(function(a, b) { return new Date(b.tarikh) - new Date(a.tarikh); });
  return { success: true, data: result };
}

function saveDokumen(token, form) {
  var auth = requireRole(token, 'Admin'); 
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Dokumen');
  var map = getColumnMap(sheet);
  
  form.tajuk = sanitizeInput(form.tajuk, 200);
  form.penerangan = sanitizeInput(form.penerangan, 500);
  if (!form.tajuk || !form.kategori || !form.link_fail) return { success: false, message: 'Maklumat wajib tidak lengkap' };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    
    if (form.isEdit === 'true') {
      var data = sheet.getDataRange().getValues();
      var found = false;
      for (var i = 1; i < data.length; i++) {
        if (String(data[i][map['id']]) === String(form.dataId)) {
          sheet.getRange(i + 1, map['tajuk'] + 1).setValue(form.tajuk);
          sheet.getRange(i + 1, map['kategori'] + 1).setValue(form.kategori);
          sheet.getRange(i + 1, map['tahun_sesi'] + 1).setValue(form.tahun_sesi);
          sheet.getRange(i + 1, map['tarikh'] + 1).setValue(form.tarikh);
          sheet.getRange(i + 1, map['penerangan'] + 1).setValue(form.penerangan);
          sheet.getRange(i + 1, map['link_fail'] + 1).setValue(form.link_fail);
          sheet.getRange(i + 1, map['tag'] + 1).setValue(form.tag);
          sheet.getRange(i + 1, map['keizinan'] + 1).setValue(form.keizinan);
          found = true;
          break;
        }
      }
      if (!found) throw new Error('Evidens tidak dijumpai');
      logAction(auth.username, 'UPDATE_DOC', 'Evidens ID: ' + form.dataId);
    } else {
      var newId = new Date().getTime();
      var rowData = [];
      rowData[map['id']] = newId;
      rowData[map['tajuk']] = form.tajuk;
      rowData[map['kategori']] = form.kategori;
      rowData[map['tahun_sesi']] = form.tahun_sesi;
      rowData[map['tarikh']] = form.tarikh;
      rowData[map['penerangan']] = form.penerangan;
      rowData[map['link_fail']] = form.link_fail;
      rowData[map['tag']] = form.tag;
      rowData[map['keizinan']] = form.keizinan;
      rowData[map['created_at']] = safeDateFormat(new Date());
      sheet.appendRow(rowData);
      logAction(auth.username, 'CREATE_DOC', 'Evidens: ' + form.tajuk);
    }
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deleteDokumen(token, id) {
  var auth = requireRole(token, 'Admin');
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Dokumen');
    var data = sheet.getDataRange().getValues();
    var map = getColumnMap(sheet);
    
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['id']]) === String(id)) {
        sheet.deleteRow(i + 1);
        logAction(auth.username, 'DELETE_DOC', 'Evidens ID: ' + id);
        return { success: true };
      }
    }
    return { success: false, message: 'Data tidak wujud' };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

// ==========================================
// 5. USER MANAGEMENT API (ADMIN ONLY)
// ==========================================
function getUsers(token) {
  var auth = requireRole(token, 'Admin');
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  var data = sheet.getDataRange().getValues();
  var map = getColumnMap(sheet);
  var result = [];

  for (var i = 1; i < data.length; i++) {
    result.push({
      username: data[i][map['username']],
      fullname: data[i][map['fullname']],
      role: data[i][map['role']]
    });
  }
  return { success: true, data: result };
}

function saveUser(token, form) {
  var auth = requireRole(token, 'Admin');
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };

  form.username = sanitizeInput(form.username, 50).toLowerCase();
  form.fullname = sanitizeInput(form.fullname, 100);
  
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
    var data = sheet.getDataRange().getValues();
    var map = getColumnMap(sheet);
    
    if (form.isEdit === 'true') {
      for (var i = 1; i < data.length; i++) {
        if (String(data[i][map['username']]) === form.username) {
          sheet.getRange(i + 1, map['fullname'] + 1).setValue(form.fullname);
          sheet.getRange(i + 1, map['role'] + 1).setValue(form.role);
          if (form.password) {
            sheet.getRange(i + 1, map['password'] + 1).setValue(hashPassword(form.password));
          }
          logAction(auth.username, 'UPDATE_USER', 'Username: ' + form.username);
          return { success: true };
        }
      }
      throw new Error('Pengguna tidak dijumpai');
    } else {
      for (var j = 1; j < data.length; j++) {
        if (String(data[j][map['username']]) === form.username) throw new Error('ID Pengguna telah wujud');
      }
      sheet.appendRow([form.username, hashPassword(form.password), form.fullname, form.role]);
      logAction(auth.username, 'CREATE_USER', 'Username: ' + form.username);
      return { success: true };
    }
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deleteUser(token, username) {
  var auth = requireRole(token, 'Admin');
  if (!auth.authorized) return { success: false, message: auth.message, sessionExpired: auth.sessionExpired };
  
  if (username === auth.username) return { success: false, message: 'Tidak boleh padam akaun sendiri.' };

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
    var data = sheet.getDataRange().getValues();
    var map = getColumnMap(sheet);
    
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['username']]) === username) {
        sheet.deleteRow(i + 1);
        logAction(auth.username, 'DELETE_USER', 'Username: ' + username);
        return { success: true };
      }
    }
    return { success: false, message: 'Pengguna tidak wujud' };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}
